inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Max: 120

Lint/AssignmentInCondition:
  Exclude:
    - 'lib/tasks/open_weather_api.rake'