default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: newshy_development

test:
  <<: *default
  database: newshy_test

production:
  <<: *default
  database: newshy_production
  username: newshy
  password: <%= ENV['NEWSHY_DATABASE_PASSWORD'] %>
